[package]
name = "AdventOfCodeRust"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = "fat"

[dependencies]
regex = "1.11.1"
md-5 = "0.11.0-pre.4"
base16ct = { version = "0.2.0", features = ["alloc"] }